/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_phoenix_mtxxndk_jni_MTXXJNI */

#ifndef _Included_com_phoenix_mtxxndk_jni_MTXXJNI
#define _Included_com_phoenix_mtxxndk_jni_MTXXJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_phoenix_mtxxndk_jni_MTXXJNI
 * Method:    getNDKWhiteRichBeauty
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_phoenix_mtxxndk_jni_MTXXJNI_getNDKWhiteRichBeauty
  (JNIEnv *, jclass, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
